# Generated by Django 5.1.6 on 2025-02-15 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenicSpot',

            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='景区名称')),
                ('description', models.TextField(verbose_name='景区描述')),
                ('location', models.CharField(max_length=200, verbose_name='景区位置')),

                ('image', models.ImageField(blank=True, null=True, upload_to='scenic_spots/', verbose_name='景区图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='景点图片'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='电子邮件'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour_date',
            field=models.DateField(verbose_name='旅游日期'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='电话')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='头像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
