# Generated by Django 5.1.6 on 2025-02-15 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_email_remove_booking_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.food'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.room'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='scenic_spot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.scenicspot'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour_date',
            field=models.DateField(blank=True, null=True, verbose_name='旅游日期'),
        ),
    ]
