# Generated by Django 5.1.6 on 2025-02-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_food_booking_room_alter_booking_scenic_spot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/', verbose_name='付款截图'),
        ),
    ]
